CREATE SCHEMA pharmacy AUTHORIZATION DBA;

CREATE TABLE  pharmacy.roles (  code VARCHAR(45) NOT NULL,  PRIMARY KEY (code));
CREATE TABLE pharmacy.users (  id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,  login VARCHAR(45) NOT NULL,  password VARCHAR(65) NOT NULL,  name VARCHAR(45) NOT NULL,  age INTEGER NULL,  roles_code VARCHAR(45) NOT NULL,  email VARCHAR(45) NULL,  telephone_number VARCHAR(45) NOT NULL,  work_place VARCHAR(100) NULL,  specialization VARCHAR(100) NULL,  salt VARCHAR(45) NULL,  PRIMARY KEY (id),  CONSTRAINT fk_users_roles1    FOREIGN KEY (roles_code)    REFERENCES pharmacy.roles (code)    ON DELETE NO ACTION    ON UPDATE NO ACTION);

INSERT INTO pharmacy.roles (code) VALUES ('PHARMACIST');
INSERT INTO pharmacy.roles (code) VALUES ('CUSTOMER');
INSERT INTO pharmacy.roles (code) VALUES ('DOCTOR');
INSERT INTO pharmacy.users (login, password, name, roles_code, telephone_number) VALUES ('sidorov_n', '12345', 'Николай Сидоров', 'DOCTOR', '+375336454545');
INSERT INTO pharmacy.users (login, password, name, roles_code, telephone_number) VALUES ('sergeev_p', '12345', 'Петр Сергеев', 'DOCTOR', '+375336545678');
UPDATE pharmacy.users SET work_place = 'ЦРБ г.Молодечно', specialization = 'ЛОР' WHERE (id = '3');
UPDATE pharmacy.users SET work_place = 'МЦ МедЦентр', specialization = 'Хирург' WHERE (id = '4');
